const { Client, Collection, Intents } = require("discord.js");
const client = global.client = new Client({
  intents: [
    Intents.FLAGS.GUILDS,
    Intents.FLAGS.GUILD_MEMBERS,
    Intents.FLAGS.GUILD_MESSAGES,
    Intents.FLAGS.GUILD_VOICE_STATES,
    Intents.FLAGS.GUILD_PRESENCES,
  ]
});
const dotenv = require("dotenv");
dotenv.config();
const config = require("./config");
const { readdir } = require("fs");
require("moment-duration-format");
const commands = client.commands = new Collection();
const aliases = client.aliases = new Collection();
client.cooldown = new Map();
client.commandblocked = [];

require("./src/helpers/function")(client);

readdir("./src/commands/", (err, files) => {
  if (err) console.error(err)
  files.forEach(f => {
    readdir("./src/commands/" + f, (err2, files2) => {
      if (err2) console.log(err2)
      files2.forEach(file => {
        let prop = require(`./src/commands/${f}/` + file);
        console.log(`[BORANGÖKDEN-COMMAND] ${prop.name} yüklendi!`);
        commands.set(prop.name, prop);
        prop.aliases.forEach(alias => {
          aliases.set(alias, prop.name);
        });
      });
    });
  });
});

readdir("./src/events", (err, files) => {
  if (err) return console.error(err);
  files.filter((file) => file.endsWith(".js")).forEach((file) => {
    let prop = require(`./src/events/${file}`);
    if (!prop.conf) return;
    client.on(prop.conf.name, prop);
    console.log(`[BORANGÖKDEN-EVENTS] ${prop.conf.name} yüklendi!`);
  });
});

client.login(config.bot.token)
  .then(() => console.log(`[BORANGÖKDEN-BOT] ${client.user.username} adıyla discord api bağlantısı kuruldu başarıyla giriş yaptı!`))
  .catch((err) => console.log(`[BORANGÖKDEN-BOT] Bot Giriş yapamadı sebep: ${err}`));

  client.on('messageCreate', async message => {
    const cdb = require("quick.db")
    const author = message.author
    if(message.guild){
      const data1 = cdb.get("cd1."+message.guild.id)
      const data2 = cdb.get("cd2."+message.channel.id+message.guild.id)
      
      if(data1){
      const blacklist = ["ag","ağzına sıçayım","ahmak","allahını","allahsız","am","amarım","ambiti","am biti","amcığı", "amcığın",  "amcığını","amcığınızı","amcık","amcık hoşafı","amcıklama","amcıklandı","amcik","amck","amckl","amcklama","amcklaryla",
      "amckta","amcktan","amcuk","amık","amına","amınako","amına koy","amına koyarım","amına koyayım","amınakoyim","amına koyyim","amına s","amına sikem","amına sokam","amın feryadı","amını","amını s","amın oglu","amınoğlu","amın oğlu","amısına",
      "amısını","amina","amina g","amina k","aminako","aminakoyarim","amina koyarim","amina koyayım","amina koyayim","aminakoyim","aminda","amindan","amindayken","amini","aminiyarraaniskiim","aminoglu","amin oglu","amiyum","amk","amkafa","amk çocuğu",
      "amlarnzn","amlı","amm","ammak","ammna","amn","amna","amnda","amndaki","amngtn","amnn","amona","amq","amsız","amsiz","amsz","amteri","amugaa","amuğa","amuna","ana","anaaann","anal","analarn","anam","anamla","anan","anana","anandan","ananı","ananı",
      "ananın","ananın am","ananın amı","ananın dölü","ananınki","ananısikerim","ananı sikerim","ananısikeyim","ananı sikeyim","ananızın","ananızın am","anani","ananin","ananisikerim","anani sikerim","ananisikeyim","anani sikeyim","anann","ananz","anas",
      "anasını","anasının am","anası orospu","anasi","anasinin","anay","anayin","angut","anneni","annenin","annesiz","anuna","aptal","aq","a.q","a.q.","aq.","ass","atkafası","atmık","attırdığım","attrrm","auzlu","avrat","ayklarmalrmsikerim","azdım","azdır",
      "azdırıcı","babaannesi kaşar","babanı","babanın","babani","babası pezevenk","bacağına sıçayım","bacına","bacını","bacının","bacini","bacn","bacndan","bacy","bastard","basur","beyinsiz","bızır","bitch","biting","bok","boka","bokbok","bokça","bokhu",
      "bokkkumu","boklar","boktan","boku","bokubokuna","bokum","bombok","boner","bosalmak","boşalmak","cenabet","cibiliyetsiz","cibilliyetini","cibilliyetsiz","cif","daltassak","dalyarak","dalyarrak","dangalak","dassagi","diktim","dildo","dingil","dingilini",
      "dinsiz","dkerim","domal","domalan","domaldı","domaldın","domalık","domalıyor","domalmak","domalmış","domalsın","domalt","domaltarak","domaltıp","domaltır","domaltırım","domaltip","domaltmak","dölü","dönek","düdük","eben","ebeni","ebenin","ebeninki","ebleh",
      "fahise",
      "fahişe",
      "feriştah",
      "ferre",
      "fuck",
      "fucker",
      "fuckin",
      "fucking",
      "gavad",
      "gavat",
      "geber",
      "geberik",
      "gebermek",
      "gebermiş",
      "gebertir",
      "gerızekalı",
      "gerizekalı",
      "gerizekali",
      "gerzek",
      "giberim",
      "giberler",
      "gibis",
      "gibiş",
      "gibmek",
      "gibtiler",
      "goddamn",
      "godoş",
      "godumun",
      "gotelek",
      "gotlalesi",
      "gotlu",
      "gotten",
      "gotundeki",
      "gotunden",
      "gotune",
      "gotunu",
      "gotveren",
      "goyiim",
      "goyum",
      "goyuyim",
      "goyyim",
      "göt",
      "göt deliği",
      "götelek",
      "göt herif",
      "götlalesi",
      "götlek",
      "götoğlanı",
      "göt oğlanı",
      "götoş",
      "götten",
      "götü",
      "götün",
      "götüne",
      "götünekoyim",
      "götüne koyim",
      "götünü",
      "götveren",
      "göt veren",
      "göt verir",
      "gtelek",
      "gtn",
      "gtnde",
      "gtnden",
      "gtne",
      "gtten",
      "gtveren",
      "hasiktir",
      "hassikome",
      "hassiktir",
      "has siktir",
      "hassittir",
      "haysiyetsiz",
      "hayvan herif",
      "hoşafı",
      "hödük",
      "hsktr",
      "huur",
      "ıbnelık",
      "ibina",
      "ibine",
      "ibinenin",
      "ibne",
      "ibnedir",
      "ibneleri",
      "ibnelik",
      "ibnelri",
      "ibneni",
      "ibnenin",
      "ibnerator",
      "ibnesi",
      "idiot",
      "idiyot",
      "imansz",
      "ipne",
      "iserim",
      "işerim",
      "itoğlu it",
      "kafam girsin",
      "kafasız",
      "kafasiz",
      "kahpe",
      "kahpenin",
      "kahpenin feryadı",
      "kaka",
      "kaltak",
      "kancık",
      "kancik",
      "kappe",
      "karhane",
      "kaşar",
      "kavat",
      "kavatn",
      "kaypak",
      "kayyum",
      "kerane",
      "kerhane",
      "kerhanelerde",
      "kevase",
      "kevaşe",
      "kevvase",
      "koca göt",
      "koduğmun",
      "koduğmunun",
      "kodumun",
      "kodumunun",
      "koduumun",
      "koyarm",
      "koyayım",
      "koyiim",
      "koyiiym",
      "koyim",
      "koyum",
      "koyyim",
      "krar",
      "kukudaym",
      "laciye boyadım",
      "lavuk",
      "liboş",
      "madafaka",
      "mal",
      "malafat",
      "malak",
      "manyak",
      "mcik",
      "meme",
      "memelerini",
      "mezveleli",
      "minaamcık",
      "mincikliyim",
      "mna",
      "monakkoluyum",
      "motherfucker",
      "mudik",
      "oc",
      "ocuu",
      "ocuun",
      "OÇ",
      "oç",
      "o. çocuğu",
      "oğlan",
      "oğlancı",
      "oğlu it",
      "orosbucocuu",
      "orospu",
      "orospucouguv",
      "orospu cocugu",
      "orospu çoc",
      "orospuçocuğu",
      "orospu çocuğu",
      "orospu çocuğudur",
      "orospu çocukları",
      "orospudur",
      "orospular",
      "orospunun",
      "orospunun evladı",
      "orospuydu",
      "orospuyuz",
      "orostoban",
      "orostopol",
      "orrospu",
      "oruspu",
      "oruspuçocuğu",
      "oruspu çocuğu",
      "osbir",
      "ossurduum",
      "ossurmak",
      "ossuruk",
      "osur",
      "osurduu",
      "osuruk",
      "osururum",
      "otuzbir",
      "öküz",
      "öşex",
      "patlak zar",
      "penis",
      "pezevek",
      "pezeven",
      "pezeveng",
      "pezevengi",
      "pezevengin evladı",
      "pezevenk",
      "pezo",
      "pic",
      "pici",
      "picler",
      "piç",
      "piçin oğlu",
      "piç kurusu",
      "piçler",
      "pipi",
      "pipiş",
      "pisliktir",
      "porno",
      "pussy",
      "puşt",
      "puşttur",
      "rahminde",
      "revizyonist",
      "s1kerim",
      "s1kerm",
      "s1krm",
      "sakso",
      "saksofon",
      "salaak",
      "salak",
      "saxo",
      "sekis",
      "serefsiz",
      "sevgi koyarım",
      "sevişelim",
      "sexs",
      "sıçarım",
      "sıçtığım",
      "sıecem",
      "sicarsin",
      "sie",
      "sik",
      "sikdi",
      "sikdiğim",
      "sike",
      "sikecem",
      "sikem",
      "siken",
      "sikenin",
      "siker",
      "sikerim",
      "sikerler",
      "sikersin",
      "sikertir",
      "sikertmek",
      "sikesen",
      "sikesicenin",
      "sikey",
      "sikeydim",
      "sikeyim",
      "sikeym",
      "siki",
      "sikicem",
      "sikici",
      "sikien",
      "sikienler",
      "sikiiim",
      "sikiiimmm",
      "sikiim",
      "sikiir",
      "sikiirken",
      "sikik",
      "sikil",
      "sikildiini",
      "sikilesice",
      "sikilmi",
      "sikilmie",
      "sikilmis",
      "sikilmiş",
      "sikilsin",
      "sikim",
      "sikimde",
      "sikimden",
      "sikime",
      "sikimi",
      "sikimiin",
      "sikimin",
      "sikimle",
      "sikimsonik",
      "sikimtrak",
      "sikin",
      "sikinde",
      "sikinden",
      "sikine",
      "sikini",
      "sikip",
      "sikis",
      "sikisek",
      "sikisen",
      "sikish",
      "sikismis",
      "sikiş",
      "sikişen",
      "sikişme",
      "sikitiin",
      "sikiyim",
      "sikiym",
      "sikiyorum",
      "sikkim",
      "sikko",
      "sikleri",
      "sikleriii",
      "sikli",
      "sikm",
      "sikmek",
      "sikmem",
      "sikmiler",
      "sikmisligim",
      "siksem",
      "sikseydin",
      "sikseyidin",
      "siksin",
      "siksinbayav",
      "siksinler",
      "siksiz",
      "siksok",
      "siksz",
      "sikt",
      "sikti",
      "siktigimin",
      "siktigiminin",
      "siktiğim",
      "siktiğimin",
      "siktiğiminin",
      "siktii",
      "siktiim",
      "siktiimin",
      "siktiiminin",
      "siktiler",
      "siktimv",
      "siktim",
      "siktimin",
      "siktiminin",
      "siktir",
      "siktir et",
      "siktirgit",
      "siktir git",
      "siktirir",
      "siktiririm",
      "siktiriyor",
      "siktir lan",
      "siktirolgit",
      "siktir ol git",
      "sittimin",
      "sittir",
      "skcem",
      "skecem",
      "skem",
      "sker",
      "skerim",
      "skerm",
      "skeyim",
      "skiim",
      "skik",
      "skim",
      "skime",
      "skmek",
      "sksin",
      "sksn",
      "sksz",
      "sktiimin",
      "sktrr",
      "skyim",
      "slaleni",
      "sokam",
      "sokarım",
      "sokarim",
      "sokarm",
      "sokarmkoduumun",
      "sokayım",
      "sokaym",
      "sokiim",
      "soktuğumunun",
      "sokuk",
      "sokum",
      "sokuş",
      "sokuyum",
      "soxum",
      "sulaleni",
      "sülaleni",
      "sülalenizi",
      "sürtük",
      "şerefsiz",
      "şıllık",
      "taaklarn",
      "taaklarna",
      "tarrakimin",
      "tasak",
      "tassak",
      "taşak",
      "taşşak",
      "tipini s.k",
      "tipinizi s.keyim",
      "tiyniyat",
      "toplarm",
      "topsun",
      "totoş",
      "vajina",
      "vajinanı",
      "veled",
      "veledizina",
      "veled i zina",
      "verdiimin",
      "weled",
      "weledizina",
      "whore",
      "xikeyim",
      "yaaraaa",
      "yalama",
      "yalarım",
      "yalarun",
      "yaraaam",
      "yarak",
      "yaraksız",
      "yaraktr",
      "yaram",
      "yaraminbasi",
      "yaramn",
      "yararmorospunun",
      "yarra",
      "yarraaaa",
      "yarraak",
      "yarraam",
      "yarraamı",
      "yarragi",
      "yarragimi",
      "yarragina",
      "yarragindan",
      "yarragm",
      "yarrağ",
      "yarrağım",
      "yarrağımı",
      "yarraimin",
      "yarrak",
      "yarram",
      "yarramin",
      "yarraminbaşı",
      "yarramn",
      "yarran",
      "yarrana",
      "yarrrak",
      "yavak",
      "yavş",
      "yavşak",
      "yavşaktır",
      "yavuşak",
      "yılışık",
      "yilisik",
      "yogurtlayam",
      "yoğurtlayam",
      "yrrak",
      "zıkkımım",
      "zibidi",
      "zigsin",
      "zikeyim",
      "zikiiim",
      "zikiim",
      "zikik",
      "zikim",
      "ziksiiin",
      "ziksiin",
      "zulliyetini"]      
      let content = message.content.split(' ');
      
      content.forEach(kelime => {
      if(blacklist.some(küfür => küfür === kelime))  {
      if(!message.member.permissions.has('BAN_MEMBERS')){
        message.delete({ timeout: 3000 });
        message.channel.send({content: `${author} sunucumuzda küfür edemezsin.` }).catch(e => {})
      message.delete().catch(e => {})
      }
      }
      })
      }
    
      if(!data1 && data2){
      const blacklist = ["ag","ağzına sıçayım","ahmak","allahını","allahsız","am","amarım","ambiti","am biti","amcığı", "amcığın",  "amcığını","amcığınızı","amcık","amcık hoşafı","amcıklama","amcıklandı","amcik","amck","amckl","amcklama","amcklaryla",
      "amckta","amcktan","amcuk","amık","amına","amınako","amına koy","amına koyarım","amına koyayım","amınakoyim","amına koyyim","amına s","amına sikem","amına sokam","amın feryadı","amını","amını s","amın oglu","amınoğlu","amın oğlu","amısına",
      "amısını","amina","amina g","amina k","aminako","aminakoyarim","amina koyarim","amina koyayım","amina koyayim","aminakoyim","aminda","amindan","amindayken","amini","aminiyarraaniskiim","aminoglu","amin oglu","amiyum","amk","amkafa","amk çocuğu",
      "amlarnzn","amlı","amm","ammak","ammna","amn","amna","amnda","amndaki","amngtn","amnn","amona","amq","amsız","amsiz","amsz","amteri","amugaa","amuğa","amuna","ana","anaaann","anal","analarn","anam","anamla","anan","anana","anandan","ananı","ananı",
      "ananın","ananın am","ananın amı","ananın dölü","ananınki","ananısikerim","ananı sikerim","ananısikeyim","ananı sikeyim","ananızın","ananızın am","anani","ananin","ananisikerim","anani sikerim","ananisikeyim","anani sikeyim","anann","ananz","anas",
      "anasını","anasının am","anası orospu","anasi","anasinin","anay","anayin","angut","anneni","annenin","annesiz","anuna","aptal","aq","a.q","a.q.","aq.","ass","atkafası","atmık","attırdığım","attrrm","auzlu","avrat","ayklarmalrmsikerim","azdım","azdır",
      "azdırıcı","babaannesi kaşar","babanı","babanın","babani","babası pezevenk","bacağına sıçayım","bacına","bacını","bacının","bacini","bacn","bacndan","bacy","bastard","basur","beyinsiz","bızır","bitch","biting","bok","boka","bokbok","bokça","bokhu",
      "bokkkumu","boklar","boktan","boku","bokubokuna","bokum","bombok","boner","bosalmak","boşalmak","cenabet","cibiliyetsiz","cibilliyetini","cibilliyetsiz","cif","daltassak","dalyarak","dalyarrak","dangalak","dassagi","diktim","dildo","dingil","dingilini",
      "dinsiz","dkerim","domal","domalan","domaldı","domaldın","domalık","domalıyor","domalmak","domalmış","domalsın","domalt","domaltarak","domaltıp","domaltır","domaltırım","domaltip","domaltmak","dölü","dönek","düdük","eben","ebeni","ebenin","ebeninki","ebleh",
      "fahise",
      "fahişe",
      "feriştah",
      "ferre",
      "fuck",
      "fucker",
      "fuckin",
      "fucking",
      "gavad",
      "gavat",
      "geber",
      "geberik",
      "gebermek",
      "gebermiş",
      "gebertir",
      "gerızekalı",
      "gerizekalı",
      "gerizekali",
      "gerzek",
      "giberim",
      "giberler",
      "gibis",
      "gibiş",
      "gibmek",
      "gibtiler",
      "goddamn",
      "godoş",
      "godumun",
      "gotelek",
      "gotlalesi",
      "gotlu",
      "gotten",
      "gotundeki",
      "gotunden",
      "gotune",
      "gotunu",
      "gotveren",
      "goyiim",
      "goyum",
      "goyuyim",
      "goyyim",
      "göt",
      "göt deliği",
      "götelek",
      "göt herif",
      "götlalesi",
      "götlek",
      "götoğlanı",
      "göt oğlanı",
      "götoş",
      "götten",
      "götü",
      "götün",
      "götüne",
      "götünekoyim",
      "götüne koyim",
      "götünü",
      "götveren",
      "göt veren",
      "göt verir",
      "gtelek",
      "gtn",
      "gtnde",
      "gtnden",
      "gtne",
      "gtten",
      "gtveren",
      "hasiktir",
      "hassikome",
      "hassiktir",
      "has siktir",
      "hassittir",
      "haysiyetsiz",
      "hayvan herif",
      "hoşafı",
      "hödük",
      "hsktr",
      "huur",
      "ıbnelık",
      "ibina",
      "ibine",
      "ibinenin",
      "ibne",
      "ibnedir",
      "ibneleri",
      "ibnelik",
      "ibnelri",
      "ibneni",
      "ibnenin",
      "ibnerator",
      "ibnesi",
      "idiot",
      "idiyot",
      "imansz",
      "ipne",
      "iserim",
      "işerim",
      "itoğlu it",
      "kafam girsin",
      "kafasız",
      "kafasiz",
      "kahpe",
      "kahpenin",
      "kahpenin feryadı",
      "kaka",
      "kaltak",
      "kancık",
      "kancik",
      "kappe",
      "karhane",
      "kaşar",
      "kavat",
      "kavatn",
      "kaypak",
      "kayyum",
      "kerane",
      "kerhane",
      "kerhanelerde",
      "kevase",
      "kevaşe",
      "kevvase",
      "koca göt",
      "koduğmun",
      "koduğmunun",
      "kodumun",
      "kodumunun",
      "koduumun",
      "koyarm",
      "koyayım",
      "koyiim",
      "koyiiym",
      "koyim",
      "koyum",
      "koyyim",
      "krar",
      "kukudaym",
      "laciye boyadım",
      "lavuk",
      "liboş",
      "madafaka",
      "mal",
      "malafat",
      "malak",
      "manyak",
      "mcik",
      "meme",
      "memelerini",
      "mezveleli",
      "minaamcık",
      "mincikliyim",
      "mna",
      "monakkoluyum",
      "motherfucker",
      "mudik",
      "oc",
      "ocuu",
      "ocuun",
      "OÇ",
      "oç",
      "o. çocuğu",
      "oğlan",
      "oğlancı",
      "oğlu it",
      "orosbucocuu",
      "orospu",
      "orospucouguv",
      "orospu cocugu",
      "orospu çoc",
      "orospuçocuğu",
      "orospu çocuğu",
      "orospu çocuğudur",
      "orospu çocukları",
      "orospudur",
      "orospular",
      "orospunun",
      "orospunun evladı",
      "orospuydu",
      "orospuyuz",
      "orostoban",
      "orostopol",
      "orrospu",
      "oruspu",
      "oruspuçocuğu",
      "oruspu çocuğu",
      "osbir",
      "ossurduum",
      "ossurmak",
      "ossuruk",
      "osur",
      "osurduu",
      "osuruk",
      "osururum",
      "otuzbir",
      "öküz",
      "öşex",
      "patlak zar",
      "penis",
      "pezevek",
      "pezeven",
      "pezeveng",
      "pezevengi",
      "pezevengin evladı",
      "pezevenk",
      "pezo",
      "pic",
      "pici",
      "picler",
      "piç",
      "piçin oğlu",
      "piç kurusu",
      "piçler",
      "pipi",
      "pipiş",
      "pisliktir",
      "porno",
      "pussy",
      "puşt",
      "puşttur",
      "rahminde",
      "revizyonist",
      "s1kerim",
      "s1kerm",
      "s1krm",
      "sakso",
      "saksofon",
      "salaak",
      "salak",
      "saxo",
      "sekis",
      "serefsiz",
      "sevgi koyarım",
      "sevişelim",
      "sexs",
      "sıçarım",
      "sıçtığım",
      "sıecem",
      "sicarsin",
      "sie",
      "sik",
      "sikdi",
      "sikdiğim",
      "sike",
      "sikecem",
      "sikem",
      "siken",
      "sikenin",
      "siker",
      "sikerim",
      "sikerler",
      "sikersin",
      "sikertir",
      "sikertmek",
      "sikesen",
      "sikesicenin",
      "sikey",
      "sikeydim",
      "sikeyim",
      "sikeym",
      "siki",
      "sikicem",
      "sikici",
      "sikien",
      "sikienler",
      "sikiiim",
      "sikiiimmm",
      "sikiim",
      "sikiir",
      "sikiirken",
      "sikik",
      "sikil",
      "sikildiini",
      "sikilesice",
      "sikilmi",
      "sikilmie",
      "sikilmis",
      "sikilmiş",
      "sikilsin",
      "sikim",
      "sikimde",
      "sikimden",
      "sikime",
      "sikimi",
      "sikimiin",
      "sikimin",
      "sikimle",
      "sikimsonik",
      "sikimtrak",
      "sikin",
      "sikinde",
      "sikinden",
      "sikine",
      "sikini",
      "sikip",
      "sikis",
      "sikisek",
      "sikisen",
      "sikish",
      "sikismis",
      "sikiş",
      "sikişen",
      "sikişme",
      "sikitiin",
      "sikiyim",
      "sikiym",
      "sikiyorum",
      "sikkim",
      "sikko",
      "sikleri",
      "sikleriii",
      "sikli",
      "sikm",
      "sikmek",
      "sikmem",
      "sikmiler",
      "sikmisligim",
      "siksem",
      "sikseydin",
      "sikseyidin",
      "siksin",
      "siksinbayav",
      "siksinler",
      "siksiz",
      "siksok",
      "siksz",
      "sikt",
      "sikti",
      "siktigimin",
      "siktigiminin",
      "siktiğim",
      "siktiğimin",
      "siktiğiminin",
      "siktii",
      "siktiim",
      "siktiimin",
      "siktiiminin",
      "siktiler",
      "siktimv",
      "siktim",
      "siktimin",
      "siktiminin",
      "siktir",
      "siktir et",
      "siktirgit",
      "siktir git",
      "siktirir",
      "siktiririm",
      "siktiriyor",
      "siktir lan",
      "siktirolgit",
      "siktir ol git",
      "sittimin",
      "sittir",
      "skcem",
      "skecem",
      "skem",
      "sker",
      "skerim",
      "skerm",
      "skeyim",
      "skiim",
      "skik",
      "skim",
      "skime",
      "skmek",
      "sksin",
      "sksn",
      "sksz",
      "sktiimin",
      "sktrr",
      "skyim",
      "slaleni",
      "sokam",
      "sokarım",
      "sokarim",
      "sokarm",
      "sokarmkoduumun",
      "sokayım",
      "sokaym",
      "sokiim",
      "soktuğumunun",
      "sokuk",
      "sokum",
      "sokuş",
      "sokuyum",
      "soxum",
      "sulaleni",
      "sülaleni",
      "sülalenizi",
      "sürtük",
      "şerefsiz",
      "şıllık",
      "taaklarn",
      "taaklarna",
      "tarrakimin",
      "tasak",
      "tassak",
      "taşak",
      "taşşak",
      "tipini s.k",
      "tipinizi s.keyim",
      "tiyniyat",
      "toplarm",
      "topsun",
      "totoş",
      "vajina",
      "vajinanı",
      "veled",
      "veledizina",
      "veled i zina",
      "verdiimin",
      "weled",
      "weledizina",
      "whore",
      "xikeyim",
      "yaaraaa",
      "yalama",
      "yalarım",
      "yalarun",
      "yaraaam",
      "yarak",
      "yaraksız",
      "yaraktr",
      "yaram",
      "yaraminbasi",
      "yaramn",
      "yararmorospunun",
      "yarra",
      "yarraaaa",
      "yarraak",
      "yarraam",
      "yarraamı",
      "yarragi",
      "yarragimi",
      "yarragina",
      "yarragindan",
      "yarragm",
      "yarrağ",
      "yarrağım",
      "yarrağımı",
      "yarraimin",
      "yarrak",
      "yarram",
      "yarramin",
      "yarraminbaşı",
      "yarramn",
      "yarran",
      "yarrana",
      "yarrrak",
      "yavak",
      "yavş",
      "yavşak",
      "yavşaktır",
      "yavuşak",
      "yılışık",
      "yilisik",
      "yogurtlayam",
      "yoğurtlayam",
      "yrrak",
      "zıkkımım",
      "zibidi",
      "zigsin",
      "zikeyim",
      "zikiiim",
      "zikiim",
      "zikik",
      "zikim",
      "ziksiiin",
      "ziksiin",
      "zulliyetini"]      
      let content = message.content.split(' ');
      
      content.forEach(kelime => {
      if(blacklist.some(küfür => küfür === kelime))  {
      if(!message.member.permissions.has('BAN_MEMBERS')){
        message.delete({ timeout: 3000 });
        message.channel.send({content: `${author} sunucumuzda küfür edemezsin.` }).catch(e => {})
      message.delete().catch(e => {})
      }
      }
      })
      }
      
    }
      });
  
  
  let cdb = require("quick.db");
  const reklam = [
    ".com",	".net",".xyz",".tk",".pw",".io",".me",".gg","www.",	"https","http",".gl",".org",".com.tr",
    ".biz",".rf",".gd",".az",".party",".gf"
   ];
    client.on("messageUpdate", async (old, nev) => {
    if(!old.guild) return;
    if (old.content != nev.content) {
      let i = await cdb.fetch(`reklam.${nev.member.guild.id}.durum`);
      let y = await cdb.fetch(`reklam.${nev.member.guild.id}.kanal`);
      if (i) {
      if (reklam.some(word => nev.content.includes(word))) {
      if (nev.member.permissions.has("BAN_MEMBERS")) return;
  
        const embed = new Discord.MessageEmbed()
        .setColor("BLACK")
        .setDescription(
          `${nev.author}, kullanıcısı mesajını editleyerek reklam yapmaya çalıştı.`
        )
        .addField("Reklam Mesajı:", nev.content)
        .addField("Reklam Yapılan Kanal:", nev.channel.name, true);
        message.delete({ timeout: 3000 });
        message.channel.send({content: `${author} mesajını editleyerek reklam yapamazsın.` }).catch(e => {})
        message.delete().catch(e => {}) 
      }
      } else {
      }
      if (!i) return;
    }
    });
    
    client.on("messageCreate", async msg => {
    if(!msg.guild) return;
    if (msg.author.bot) return;
    if (msg.channel.type === "dm") return;
    let y = await cdb.fetch(`reklam.${msg.member.guild.id}.kanal`);
    
    let i = await cdb.fetch(`reklam.${msg.member.guild.id}.durum`);
    if (i) {
      if (reklam.some(word => msg.content.toLowerCase().includes(word))) {
      try {
        if (!msg.member.permissions.has("MANAGE_GUILD")) {
        msg.delete({ timeout: 3000 });
        msg.channel.send({content: `${msg.author} sunucumuzda reklam yapamazsın.` }).catch(e => {})
        msg.delete().catch(e => {})
        const embed = new MessageEmbed()
          .setColor("BLACK")
          .setDescription(`${msg.author} kullanıcısı sunucumuzda reklam yapmaya çalıştı.`)
          .addField("Reklam Mesajı:", msg.content)
          .addField("Reklam Yapılan Kanal", msg.channel.name, true);
        client.channels.cache.get(y).send({ embeds: [embed]});
        }
      } catch (err) {
        console.log(err);
      }
      }
    }
    if (!i) return;
  });